name: "Generic Task"
description: "Create a generic task item"
projects: ["expansion-games/1"]
type: "Task"
body:
  - type: markdown
    attributes:
      value: |
        ## :warning: Public Repository
        Your issue will be created in the public issues repository. While issues are public by default, some issues are not appropriate for this repository. 
        Create an [internal issue](https://github.com/expansion-games/site-delta/issues/new/choose) instead if there are sensitive or otherwise confidential details.
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "What needs to be completed before the task can be defined as \"done\"?"
      value: |
        - User should be able to ...
        ...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Task Details"
      description: "Any additional details to provide to the developer"
      value: |
        - As a ... I want to ... so that ...
    validations:
      required: false
